FROM hub.cism-ms.ru/library/python:3.10 as back

ARG DEV_ENV
WORKDIR /opt/project/app

ENV PYTHONBUFFERED=1
RUN apt install --reinstall tzdata
ENV TZ=Europe/Moscow
RUN cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime

# Устанавливаем Poetry
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VERSION=1.8.3
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="${POETRY_HOME}/bin:${PATH}"


COPY src/backend/pyproject.toml src/backend/poetry.lock

COPY src/backend /opt/project/app
RUN rm -rf /opt/project/app/.env

COPY devops/scripts scripts

RUN apt update && apt install -y htop nano
RUN chmod +x scripts/*.sh; sync; scripts/install_packages.sh $DEV_ENV

EXPOSE 5000
CMD poetry run /opt/project/app/scripts/run_backend.sh
