{
 "title": "cism-app",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество запросов в сек",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(http_request_duration_seconds_count{handler!=\"none\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибки/в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_request_duration_seconds_count{status=~\"4.+|5.+\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время выполнения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler!=\"none\"}[5m]))by(le,handler))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процент ошибок",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"4.+|5.+\"}[5m])) / sum(increase(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}